In [2]:
import pandas as pd

In [3]:
fieldContact_df = pd.read_csv("fio-records-2022-mark43-fieldcontact-table.csv")

In [4]:
fieldContactName_df = pd.read_csv("fio-records-2022-mark43-fieldcontact_name-table.csv")

In [5]:
fieldContact_df.head()

,fc_num,contact_date,contact_officer,contact_officer_name,supervisor,supervisor_name,street,city,state,zip,...,basis,vehicle_year,vehicle_state,vehicle_model,vehicle_color,vehicle_style,vehicle_type,key_situations,contact_reason,weather
0,FC22000008,2022-01-01 00:00:00,151206,"WATTY-NILES, CREFTON",11586,CHRISTOPHER CARROLL,ALBANY ST,BOSTON,MA,2118,...,Reasonable Suspicion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01/01/2022 11:40 PM\n\nOfficers responded to a...,NaN
1,FC22000001,2022-01-01 02:30:00,153132,"VILLEGAS-HOAG, STEPHANIE",11212,MICHAEL MCCARTHY,NaN,BOSTON,MA,2122,...,Probable Cause,2008.0,MA,Taurus,Brown,"4 Door, Sedan",Passenger Car/ Automobile,NaN,"About 02:30am, Officers assisted State Police ...",NaN
2,FC22000004,2022-01-01 09:29:00,148290,"PARHAM, ANTHONY",10845,JAMES MOORE,BRIARCLIFF,MATTAPAN,MA,2126,...,Encounter,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"About 10:00AM, Saturday 1/1/21 Officers respon...",NaN
3,FC22000003,2022-01-01 10:16:00,162319,"Uhrig, Robert",9266,STEVEN CICCOLO,E EIGHTH ST,SOUTH BOSTON,MA,2127,...,Reasonable Suspicion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"About 10:16am on Saturday, 01/01/22, Officers ...",NaN
4,FC22000005,2022-01-01 10:29:00,100417,"FLYNN, THOMAS",11212,MICHAEL MCCARTHY,ROBINSON ST,DORCHESTER,MA,2122,...,Probable Cause,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Officers responded to a radio call for a B&E t...,NaN

In [6]:
fieldContactName_df.head()

,person_id,contact_date,fc_num,sex,race,age,build,hair_style,ethnicity,skin_tone,deceased,license_type,license_state,was_frisked
0,30750626451,2022-01-01 00:00:00.0000000,FC22000008,Male,Black,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0
1,30745256091,2022-01-01 02:30:00.0000000,FC22000001,Male,Black,25.0,Thin,Short,Not of Hispanic Origin,Brown,0,Personal Driver License,MA,1.0
2,30747685932,2022-01-01 09:29:00.0000000,FC22000004,Male,Black,39.0,Medium,Bald or Balding,Not of Hispanic Origin,Medium Brown,0,Class D,MA,1.0
3,30747687157,2022-01-01 09:29:00.0000000,FC22000004,Female,Black,35.0,NaN,NaN,Not of Hispanic Origin,NaN,0,Class D,MA,NaN
4,30747589299,2022-01-01 10:16:00.0000000,FC22000003,Male,White,54.0,Medium,NaN,Not of Hispanic Origin,NaN,0,NaN,NaN,0.0

In [7]:
print(fieldContact_df.shape)
print(fieldContactName_df.shape)

(5278, 22)
(9408, 14)

In [8]:
print(len(fieldContact_df['fc_num'].unique()))
print(len(fieldContactName_df['fc_num'].unique()))

5124
5254

In [9]:
# Merging both field contact and field contact name dataframes
fio_df = pd.merge(fieldContact_df, fieldContactName_df, how='inner', left_on = 'fc_num', right_on = 'fc_num')

In [10]:
fio_df.shape

(9458, 35)

In [11]:
fio_df.head(20)

,fc_num,contact_date_x,contact_officer,contact_officer_name,supervisor,supervisor_name,street,city,state,zip,...,race,age,build,hair_style,ethnicity,skin_tone,deceased,license_type,license_state,was_frisked
0,FC22000008,2022-01-01 00:00:00,151206,"WATTY-NILES, CREFTON",11586,CHRISTOPHER CARROLL,ALBANY ST,BOSTON,MA,2118,...,Black,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0
1,FC22000001,2022-01-01 02:30:00,153132,"VILLEGAS-HOAG, STEPHANIE",11212,MICHAEL MCCARTHY,NaN,BOSTON,MA,2122,...,Black,25.0,Thin,Short,Not of Hispanic Origin,Brown,0,Personal Driver License,MA,1.0
2,FC22000004,2022-01-01 09:29:00,148290,"PARHAM, ANTHONY",10845,JAMES MOORE,BRIARCLIFF,MATTAPAN,MA,2126,...,Black,39.0,Medium,Bald or Balding,Not of Hispanic Origin,Medium Brown,0,Class D,MA,1.0
3,FC22000004,2022-01-01 09:29:00,148290,"PARHAM, ANTHONY",10845,JAMES MOORE,BRIARCLIFF,MATTAPAN,MA,2126,...,Black,35.0,NaN,NaN,Not of Hispanic Origin,NaN,0,Class D,MA,NaN
4,FC22000003,2022-01-01 10:16:00,162319,"Uhrig, Robert",9266,STEVEN CICCOLO,E EIGHTH ST,SOUTH BOSTON,MA,2127,...,White,54.0,Medium,NaN,Not of Hispanic Origin,NaN,0,NaN,NaN,0.0
5,FC22000003,2022-01-01 10:16:00,162319,"Uhrig, Robert",9266,STEVEN CICCOLO,E EIGHTH ST,SOUTH BOSTON,MA,2127,...,White,44.0,NaN,NaN,Unknown,NaN,0,ID Only - Never had Personal Driver License,MA,0.0
6,FC22000005,2022-01-01 10:29:00,100417,"FLYNN, THOMAS",11212,MICHAEL MCCARTHY,ROBINSON ST,DORCHESTER,MA,2122,...,White,31.0,NaN,NaN,Not of Hispanic Origin,NaN,0,Class D,MA,0.0
7,FC22000005,2022-01-01 10:29:00,100417,"FLYNN, THOMAS",11212,MICHAEL MCCARTHY,ROBINSON ST,DORCHESTER,MA,2122,...,Black,35.0,Medium,Short,NaN,Medium Brown,0,Class D,MA,0.0
8,FC22000006,2022-01-01 11:50:00,148310,"VERDERICO, JAMES",9021,THOMAS HOPKINS,ALBANY ST,BOSTON,MA,2118,...,White,39.0,Medium,Short,Not of Hispanic Origin,NaN,0,Class D,MA,0.0
9,FC22000007,2022-01-01 19:35:00,90495,"FLAVEN, MICHAEL",11827,MICHAEL MYLETT,GEORGETOWNE DR,HYDE PARK,MA,2136,...,Black,40.0,NaN,NaN,Not of Hispanic Origin,NaN,0,Class D,MA,1.0
10,FC22000007,2022-01-01 19:35:00,90495,"FLAVEN, MICHAEL",11827,MICHAEL MYLETT,GEORGETOWNE DR,HYDE PARK,MA,2136,...,Black,41.0,NaN,NaN,Not of Hispanic Origin,NaN,0,NaN,MA,0.0
11,FC22000007,2022-01-01 19:35:00,90495,"FLAVEN, MICHAEL",11827,MICHAEL MYLETT,GEORGETOWNE DR,HYDE PARK,MA,2136,...,Black,38.0,NaN,NaN,Not of Hispanic Origin,NaN,0,NaN,NaN,0.0
12,FC22000009,2022-01-01 23:59:00,157666,"MEJIA, KAREN",131216,ZACHARY CROSSEN,COMMERCIAL ST,BOSTON,MA,2109,...,White,31.0,NaN,NaN,Not of Hispanic Origin,NaN,0,NaN,PA,0.0
13,FC22000009,2022-01-01 23:59:00,157666,"MEJIA, KAREN",131216,ZACHARY CROSSEN,COMMERCIAL ST,BOSTON,MA,2109,...,White,28.0,NaN,NaN,Hispanic Origin,NaN,0,NaN,PA,0.0
14,FC22000016,2022-01-02 01:06:00,148281,"KERRIGAN, CHRISTOPHER",9378,THOMAS O'LEARY,WASHINGTON ST,ROXBURY,MA,2119,...,Black,42.0,NaN,NaN,Not of Hispanic Origin,NaN,0,Class D,MA,NaN
15,FC22000016,2022-01-02 01:06:00,148281,"KERRIGAN, CHRISTOPHER",9378,THOMAS O'LEARY,WASHINGTON ST,ROXBURY,MA,2119,...,Black,48.0,NaN,NaN,Not of Hispanic Origin,NaN,0,NaN,NaN,0.0
16,FC22000010,2022-01-02 01:15:00,153081,"LEWIS, JOHNATHAN",10845,JAMES MOORE,GREENWOOD ST,DORCHESTER,MA,2121,...,Unknown,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0
17,FC22000012,2022-01-02 09:45:00,111241,"MUSTACCHIO, MICHAEL",131216,ZACHARY CROSSEN,NaN,BOSTON,MA,2114,...,White,67.0,Thin,NaN,Not of Hispanic Origin,NaN,0,Class D,MA,0.0
18,FC22000026,2022-01-02 14:20:00,140282,"ADAMS, CHRISTOPHER",12120,EDIBERTO FIGUEROA,NaN,BOSTON,MA,2119,...,Black,56.0,Medium,Short,Unknown,Medium Brown,0,NaN,MA,0.0
19,FC22000014,2022-01-02 17:00:00,162930,"McCullough, Matthew",131216,ZACHARY CROSSEN,NaN,BOSTON,MA,2111,...,Black,24.0,Thin,Short,Hispanic Origin,Medium Brown,0,Instruction Permit,MA,0.0

In [12]:
# city council 
cityCouncilDistrict_D4_zip = [2121, 2122, 2124, 2125, 2126, 2131 ]
policeDistrict_D4_zip = [2116, 2115, 2215, 2120,  2116, 2114, 2111, 2113]

In [13]:

# Filter the rows based on zip_district_4
fio_policeDistrict_D4_df = fio_df[fio_df['zip'].isin(policeDistrict_D4_zip)]
fio_cityCouncilDistrict_D4_df = fio_df[fio_df['zip'].isin(cityCouncilDistrict_D4_zip)]

In [14]:
print(fio_policeDistrict_D4_df.shape)
print(fio_cityCouncilDistrict_D4_df.shape)

(1278, 35)
(4101, 35)

In [15]:
fio_cityCouncilDistrict_D4_df.head(20)

,fc_num,contact_date_x,contact_officer,contact_officer_name,supervisor,supervisor_name,street,city,state,zip,...,race,age,build,hair_style,ethnicity,skin_tone,deceased,license_type,license_state,was_frisked
1,FC22000001,2022-01-01 02:30:00,153132,"VILLEGAS-HOAG, STEPHANIE",11212,MICHAEL MCCARTHY,NaN,BOSTON,MA,2122,...,Black,25.0,Thin,Short,Not of Hispanic Origin,Brown,0,Personal Driver License,MA,1.0
2,FC22000004,2022-01-01 09:29:00,148290,"PARHAM, ANTHONY",10845,JAMES MOORE,BRIARCLIFF,MATTAPAN,MA,2126,...,Black,39.0,Medium,Bald or Balding,Not of Hispanic Origin,Medium Brown,0,Class D,MA,1.0
3,FC22000004,2022-01-01 09:29:00,148290,"PARHAM, ANTHONY",10845,JAMES MOORE,BRIARCLIFF,MATTAPAN,MA,2126,...,Black,35.0,NaN,NaN,Not of Hispanic Origin,NaN,0,Class D,MA,NaN
6,FC22000005,2022-01-01 10:29:00,100417,"FLYNN, THOMAS",11212,MICHAEL MCCARTHY,ROBINSON ST,DORCHESTER,MA,2122,...,White,31.0,NaN,NaN,Not of Hispanic Origin,NaN,0,Class D,MA,0.0
7,FC22000005,2022-01-01 10:29:00,100417,"FLYNN, THOMAS",11212,MICHAEL MCCARTHY,ROBINSON ST,DORCHESTER,MA,2122,...,Black,35.0,Medium,Short,NaN,Medium Brown,0,Class D,MA,0.0
16,FC22000010,2022-01-02 01:15:00,153081,"LEWIS, JOHNATHAN",10845,JAMES MOORE,GREENWOOD ST,DORCHESTER,MA,2121,...,Unknown,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,0.0
20,FC22000015,2022-01-02 18:35:00,105619,"LOPES, SAMORA",10092,DANIEL TRACEY,NaN,BOSTON,MA,2124,...,Black,20.0,Thin,NaN,Hispanic Origin,NaN,0,NaN,MA,1.0
21,FC22000015,2022-01-02 18:35:00,105619,"LOPES, SAMORA",10092,DANIEL TRACEY,NaN,BOSTON,MA,2124,...,White,18.0,Thin,NaN,Hispanic Origin,NaN,0,NaN,MA,1.0
22,FC22000015,2022-01-02 18:35:00,105619,"LOPES, SAMORA",10092,DANIEL TRACEY,NaN,BOSTON,MA,2124,...,Black,18.0,NaN,NaN,Not of Hispanic Origin,NaN,0,NaN,MA,1.0
23,FC22000015,2022-01-02 18:35:00,105619,"LOPES, SAMORA",10092,DANIEL TRACEY,NaN,BOSTON,MA,2124,...,White,21.0,Medium,NaN,Hispanic Origin,NaN,0,None,MA,1.0
24,FC22000021,2022-01-02 22:15:00,124390,"COYNE, CHRISTIAN",9378,THOMAS O'LEARY,NaN,BOSTON,MA,2121,...,Black,14.0,NaN,NaN,NaN,NaN,0,NaN,NaN,1.0
25,FC22000021,2022-01-02 22:15:00,124390,"COYNE, CHRISTIAN",9378,THOMAS O'LEARY,NaN,BOSTON,MA,2121,...,White,15.0,NaN,NaN,Hispanic Origin,NaN,0,NaN,NaN,1.0
26,FC22000021,2022-01-02 22:15:00,124390,"COYNE, CHRISTIAN",9378,THOMAS O'LEARY,NaN,BOSTON,MA,2121,...,Black,18.0,NaN,NaN,Not of Hispanic Origin,NaN,0,Class D,MA,1.0
30,FC22000020,2022-01-03 12:20:00,128383,"O'CONNOR, MATTHEW",99722,JOHN BURROWS,BLUE HILL AVE,DORCHESTER,MA,2124,...,Black,17.0,Medium,Short,Not of Hispanic Origin,Dark,0,None,MA,1.0
31,FC22000020,2022-01-03 12:20:00,128383,"O'CONNOR, MATTHEW",99722,JOHN BURROWS,BLUE HILL AVE,DORCHESTER,MA,2124,...,Black,20.0,NaN,NaN,Unknown,NaN,0,Other: Class 10 - RI,RI,1.0
32,FC22000022,2022-01-03 17:03:00,157676,"PANZAVECCHIA, STEFANIA",99722,JOHN BURROWS,WESTVIEW STREET,BOSTON,MA,2124,...,Black,23.0,Thin,Dreadlocks,NaN,Medium Brown,0,Class D,MA,0.0
33,FC22000023,2022-01-03 18:21:00,126478,"BELGRAVE, FABIAN",9266,STEVEN CICCOLO,ALLSTATE RD,DORCHESTER,MA,2125,...,White,35.0,Thin,Short,Not of Hispanic Origin,Medium,0,NaN,MA,1.0
34,FC22000028,2022-01-04 20:35:00,99776,"LEVICHEV, VLADIMIR",11180,PATRICK MORRISON,KIMBALL ST,DORCHESTER,MA,2122,...,Black,33.0,Medium,NaN,Not of Hispanic Origin,NaN,0,NaN,MA,0.0
35,FC22000029,2022-01-04 20:39:00,153083,"HARRINGTON, BRIAN, F",10845,JAMES MOORE,BLUE HILL AVE,BOSTON,MA,2125,...,Other,41.0,NaN,NaN,Hispanic Origin,NaN,0,Class D,MA,NaN
36,FC22000029,2022-01-04 20:39:00,153083,"HARRINGTON, BRIAN, F",10845,JAMES MOORE,BLUE HILL AVE,BOSTON,MA,2125,...,Other,41.0,NaN,NaN,Hispanic Origin,NaN,0,Class D,MA,NaN